### ISSUE TITLE
Include #silence in LogWeasel logger

### ISSUE THREAD

**Issue by soulcutter** [stitchfix/log_weasel#6]
Problem
--------
In Rails 5 they moved the `#silence` method to a concern. This can occasionally break things when other libraries expect it to be there (see https://github.com/stitchfix/playback/pull/38).

Solution
--------
Detect rails version and include `LoggerSilence` when applicable. This prevents downstream apps that use LogWeasel from having to care about this.

**Comment by brettfishman** [comment]
This should be addressed in the newly released v `1.1.2` of this gem. Closing.
